variable "vm_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "size" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "version_name" {}
variable "nic_name" {}